### PR TITLE
[confiscan] Gather application-specific configs

### PR DESCRIPTION
**Pull request by AntonVanAssche**
Configuration files of installed application can now be specified by adding the path to the end of the argument list, no need for specifying an option. This ensures that Shell globbing is supported for `[CONFIG_FILES]`, and can be a file or directory.

For example, `./confiscan.sh /etc/sudoers /etc/sysctl.conf` will result in the following structure:

```
srv5-configs/
├── etc
│   ├── sudoers
│   └── sysctl.conf
└── ...
```

When no path is specified, the whole `/etc/` directory will be used instead.

### CODE REVIEW

**Comment by AntonVanAssche** [comment]
Maybe a cool feature would be to support brace expansion for the paths? I'm not really sure how to implement it, `eval` maybe? Perhaps support for globs would also be a cool addition? 

I know something like:

```bash
IFS=' ' read -r -a config_files <<< "$( eval echo "${OPTARG}" )"
IFS=',' read -r -a config_files <<< "${config_files[@]}"
IFS=' ' read -r -a config_files <<< "${config_files[@]}"
```

kind of works. It will result in the following output:

```console
Info: Getting config: /etc/debconf.conf
Info: Getting config: /etc/sudoers
Info: Getting config: /etc/sysctl.conf
Info: Getting config: /etc/sudoers
```

However it only works when the command was structured like: `sudo ./confiscan.sh -c '/etc/{debconf,sysctl}.conf',/etc/sudoers`, which requires the brace expansion to be quoted, and not being handled by the shell itself. Also duplicates are present when doing it this way.

**Comment by AntonVanAssche** [comment]
Removing the use of a comma as delimiter and allowing all arguments to be space separated. By default `getopts` does not support this, but requires multiple `-c`'s for this.

So the command structure would look like:

```console
$ sudo ./confiscan.sh -c /etc/debconf.conf /etc/sudoers
```

This paired with globing and brace expansion support would be cool. 😁

**Comment by AntonVanAssche** [comment]
The following code makes sure the tool supports brace expansions, globing, and multiple values for `-c`:

```bash
APP_CONFIGS=()
PARSING_APP_CONFIGS=0

while getopts ":c:ht" opt; do
    case ${opt} in
        h)
            usage
            exit 0
            ;;
        c)
            [[ -f "${OPTARG:?}" ]] || [[ -d "${OPTARG:?}" ]] || \
                error "${OPTARG} no such file or directory." 2

            PARSING_APP_CONFIGS=1
            APP_CONFIGS+=("${OPTARG:?}")
            ;;
        t)
            MAKE_TAR=1
            ;;
        \?)
            error "Invalid option: ${OPTARG}" 1
            ;;
    esac
done
shift $((OPTIND -1))

if [[ "${PARSING_APP_CONFIGS}" -eq 1 ]]; then
    while [[ ${#} -gt 0 ]]; do
        case "${1}" in
            -*)
                break
                ;;
            *)
                [[ -f "${1}" ]] || [[ -d "${1}" ]] || \
                    error "${1} no such file or directory." 2
                APP_CONFIGS+=("${1}")
                ;;
        esac
        shift
    done
fi

for c in "${APP_CONFIGS[@]}"; do
    info "Getting config: ${c}"
    mkdir -p "${output_dir}/$(dirname "${c}")"
    cp -r "${c}" "${output_dir}/$(dirname "${c}")"
done
```

Result:
```console
$ sudo ./confiscan.sh -c /etc/sysctl.conf /etc/debconf.conf /etc/bash{.bashrc,_completion}
...
Info: Getting config: /etc/sysctl.conf
Info: Getting config: /etc/debconf.conf
Info: Getting config: /etc/bash.bashrc
Info: Getting config: /etc/bash_completion
```

However it breaks the `-t` option: `./confiscan.sh: line 81: OPTARG: unbound variable`. But only when `-t` is the last argument given to the script. So maybe this is an option to require at the end of the argument list? Some other commands also have place specific options, `host` for example won't work when `-p` is given as last argument. What do you think @bdeferme?

```console
# Works:
$ sudo ./confiscan.sh -t -c /etc/sysctl.conf /etc/debconf.conf /etc/bash{.bashrc,_completion}

# Fails:
$ sudo ./confiscan.sh -c /etc/sysctl.conf /etc/debconf.conf /etc/bash{.bashrc,_completion} -t
$ echo $?
1
```

**Comment by AntonVanAssche** [comment]
When going with the approach of above, the help output could be something like:
```
Usage: confiscan.sh [OPTION]

Options:
    -h   Display help
    -c   Specify one, or more, config file(s)
    -t   Create tarball of output directory

Note:
    -c can be a file or directory.
    -c is required to be the last option, when specified.

Examples:
    confiscan.sh -h
    confiscan.sh -c /etc/sysctl.conf
    confiscan.sh -c /etc/apache2/ /etc/sysctl.conf
    confiscan.sh -t -c /etc/bash{.bashrc,_completion}
    confiscan.sh -t
```

**Comment by AntonVanAssche** [comment]
Can always revert/remove d1c44a3.

**Comment by bdeferme** [comment]
Looks good, but:

If you decide that the config files are not an option but rather a positional argument (all of them) you could have the following usage:

```
Usage: confiscan.sh [OPTION] [CONFIG_FILES]

Options:
    -h   Display help
    -t   Create tarball of output directory

Note:
    Shell globbing is supported for [CONFIG_FILES]. They can be files or directories.

Examples:
    confiscan.sh -h
    confiscan.sh /etc/sysctl.conf
    confiscan.sh /etc/apache2/ /etc/sysctl.conf
    confiscan.sh -t /etc/bash{.bashrc,_completion}
    confiscan.sh -t
```
    
This would:
- Make it clear CONFIG_FILES should be in the last position always.
- Simplify your code a lot as you would only need:

```
for c in "$@"; do
  echo "Getting config: ${c}"
done
```

**Comment by AntonVanAssche** [comment]
> Looks good, but:
> 
> If you decide that the config files are not an option but rather a positional argument (all of them) you could have the following usage:
> 
> ```
> Usage: confiscan.sh [OPTION] [CONFIG_FILES]
> 
> Options:
>     -h   Display help
>     -t   Create tarball of output directory
> 
> Note:
>     Shell globbing is supported for [CONFIG_FILES]. They can be files or directories.
> 
> Examples:
>     confiscan.sh -h
>     confiscan.sh /etc/sysctl.conf
>     confiscan.sh /etc/apache2/ /etc/sysctl.conf
>     confiscan.sh -t /etc/bash{.bashrc,_completion}
>     confiscan.sh -t
> ```
> 
> This would:
> 
>     * Make it clear CONFIG_FILES should be in the last position always.
> 
>     * Simplify your code a lot as you would only need:
> 
> 
> ```
> for c in "$@"; do
>   echo "Getting config: ${c}"
> done
> ```

Opted for this approach, changes are visible in commit: [f672384](https://github.com/AntonVanAssche/hogent-bachelorproef/pull/28/commits/f672384f85db59f6385284fec761cd4729460685). Thanks!

**Pull request merged**
